## - Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
import numpy as np

def resum_estadistic(data):
    if len(np.shape(data)) != 1:
        return "Error: l'array ha de tenir una dimensió!."
    else:
        mitja = np.mean(data)
        mitjana = np.median(data)
        desviacio_estandard = np.std(data)
        variancia = np.var(data)
        valor_maxim = np.max(data)
        valor_minim = np.min(data)
        return f"Mitja: {mitja}, Mitjana: {mitjana},Desviació estàndard: {desviacio_estandard}, Variància:{variancia}, Valor màxim:{valor_maxim}, Valor mínim:{valor_minim}"

In [3]:
resum_estadistic([1,2,35,6,6,7,7])

'Mitja: 9.142857142857142, Mitjana: 6.0,Desviació estàndard: 10.789261479142404, Variància:116.40816326530613, Valor màxim:35, Valor mínim:1'

In [4]:
resum_estadistic([[1,2,35,6,6,7,7],
                [1,3,5,6,7,7,8]])

"Error: l'array ha de tenir una dimensió!."

## - Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.




In [5]:
def omplir_matriu(n):
    return np.random.randint(0, 100, size=(n, n))
resultat = omplir_matriu(4)
print(resultat)

[[28  0  8  5]
 [61 80 73  2]
 [85 91 83 28]
 [17 74 42 78]]



## - Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.





In [6]:
def totals_fila_columna(taula):
    totals_fila = np.sum(taula, axis=1)
    totals_columna = np.sum(taula, axis=0)
    return totals_fila, totals_columna
resultat = totals_fila_columna([[2,4],[5,7]])
print(resultat)

(array([ 6, 12]), array([ 7, 11]))


## - Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [21]:
def coeficient_correlacio(x, y):
    n = len(x)
    x_mean = np.mean(x)
    y_mean = np.mean(y)
    x_diff = x - x_mean
    y_diff = y - y_mean
    numerator = np.sum(x_diff * y_diff)
    x_diff_squared = x_diff**2
    y_diff_squared = y_diff**2
    denominator = np.sqrt(np.sum(x_diff_squared) * np.sum(y_diff_squared))
    return numerator / denominator

x = np.array([165,170,195])
y = np.array([50,65,80])
correlacio = coeficient_correlacio(x, y)
print(correlacio)

0.9332565252573827


In [23]:
#Només per comprovar que coincideix, ho calculem amb una funció de Numpy. 

x = np.array([165,170,195])
y = np.array([50,65,80])  
np.corrcoef(x,y) 

array([[1.        , 0.93325653],
       [0.93325653, 1.        ]])

El coeficient de correlació mesura la relació lineal entre dues variables. Es mesura amb valors que van des del -1 al 1 i descriu la força i la direcció de la relació entre dues variables. 

Si el valor de correlació s'apropa a l'1, indica que la relació entre les dues variables és forta i positiva. Si una variable augmenta, l'altre també ho farà. Si pel contrari s'apropa al -1, vol dir que hi ha una correlació negativa: si una variable augmenta, l'altra disminueix i al revés. Si él coeficient de correlació s'apropa al 0, vol dir que la relació lineal és baixa o inexistent.